shared:
  amazon_s3: false
  allow_search: true
  daily_task_reminder_email_time: 8
  activities_per_page: 25
  email_confirmation_require: true
  app_domain: localhost:3000
  providers:
    - provider: google
      key:
      secret:
  smtp_settings:
    domain: psyjaciele.com
    safe_from: todo@psyjaciele.com
